### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by regular** [regular/ssb-electroparty#1]
@mmckegg / @alubbe  would one of you be available for hire to make a Win7 (64bit) executable of this? @mmckegg, I followed your instructions somewhere on the Scuttleverse, and I got far. But things went south (is that expression in use in NZ?) when ssb-party tried to spawn another process. (Works fine on OSX)

**Comment by alubbe** [comment]
Hi Jan - long time no speak. Are you sure you meant to ping me? I haven't used ssb so far

**Comment by regular** [comment]
@alubbe I meant you, because you use node on windows and possibly are familiar with complications with building native modules under windows?

**Comment by alubbe** [comment]
No, I have not experienced issues once things were building correctly. I assumed you were talking about a runtime error regarding additional processes?

**Comment by regular** [comment]
That's correct, but it might be a  delayed effect of leveldown not being built correctly. The error message is rather bizarre (might be because I had to use a german copy of Win7 because it is impossible to find this ancient OS these days, but it is the required target platform so I figured I probably should use it as a build environment as well)

```
[...]
dom ready
Starting scuttlebot...

Node version: v7.9.0
PACKED
spawned SBOT
C:\Users\regular\dev\ssb-electroparty\build\SSB-Electroparty-win32-x64\resources\app\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: Das System hat keinen Meldungstext für die Meldungsnummer 0x%1 in der Meldungsdatei %2 gefunden.
\\?\C:\Users\regular\dev\ssb-electroparty\build\SSB-Electroparty-win32-x64\resources\app\node_modules\leveldown\build\Release\leveldown.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\regular\dev\ssb-electroparty\build\SSB-Electroparty-win32-x64\resources\app\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\regular\dev\ssb-electroparty\build\SSB-Electroparty-win32-x64\resources\app\node_modules\leveldown\leveldown.js:4:46)
```

**Comment by regular** [comment]
The file `build\SSB-Electroparty-win32-x64\resources\app\node_modules\leveldown\build\Release\leveldown.node` does exist, butt apparently there's an issue with dynamically loading it?

**Comment by mmckegg** [comment]
@regular

This looks a lot like the sort of error you get when the native addon was built for the wrong ABI version (V8). This error pops up your installed version of Node doesn't match the electron version.

Have you tried rebuilding with electron as the target? See patchwork's package.json for an example: https://github.com/ssbc/patchwork/blob/master/package.json#L12

**Comment by regular** [comment]
@mmckegg I copied your exact script: https://github.com/regular/ssb-electroparty/blob/master/package.json#L14

I ran `npm run rebuild`, then `npm run pack`.  Electron starts up fine. When I type `require('leveldown')` into Electron's dev tools console, I get the above error message. Yea, I agree it looks a lot like an ABI version mismatch ... hm.

**Comment by regular** [comment]
Thanks for your comments! _It just works now_! For same strange reason that only the gods of Windows know, it fails when being started from git bash, but works when double clicked!

**Comment by alubbe** [comment]
Cool - now please pay us as you suggested initially :)

**Comment by mmckegg** [comment]
> For same strange reason that only the gods of Windows know, it fails when being started from git bash, but works when double clicked!

I had a lot of trouble on Windows with native addons and weird terminals too, so I've stuck with PowerShell in admin mode and never had any issues.

**Comment by regular** [comment]
@mmckegg that's good advise. For example, if I do `npm i`, I get no progress indication whatsoever when using git bash. One of my goals with electroparty is to provide generic binaries for all platforms that can be used for all kinds of different ssb-based applications. By replacing a blob reference in the config file, I can turn this windows binary into a desktop client for ssb-cms, or a social media client. So, hopefully in the future, less people will have to struggle with building native executables.
